name: Bug Report
description: File a bug report
title: ""
labels: ["triage"]
type: "bug"
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report!
        Before creating a bug report, be sure to keep the following points in mind:
        - Search existing reports to make sure there isn't already an existing bug report.
        - Make sure this is the correct project for your report. If you’re reporting a bug related to Capacitor or one of its plugins, please confirm that you’re in the appropriate repository before submitting your report.
        - Feel free to chat with us in [discussions](https://github.com/ionic-team/capacitor/discussions) if you are unsure whether something is a bug or feature request.
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: |
        Give a detailed explanation of the bug you've encountered:
        - What was the specific command or function call that failed?
        - Include the exact error message or stack trace (use code blocks!).
        - How does the actual output differ from the documentation or expected result?
        - If applicable, mention if this is a regression (did it work in a previous version?).
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "Describe what you expected to happen, or what should be the correct behavior."
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: "Include a link to a minimal test project that demonstrates the bug."
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Screenshots / Media
      description: "Include screenshots, video recordings or other collateral that helps illustrate the problem described in the bug."
    validations:
      required: false
  - type: textarea
    id: env-details
    attributes:
      label: Environment Details
      description: "Please provide the following information with your request and any other relevant technical details (versions of IDEs, local environment info, plugin information or links, etc)."
      placeholder: |
        OS version:
        `npx cap doctor` output:
        npm --version output:
        node --version output:
        pod --version output (iOS Cocoapods issues only):
      render: Shell
    validations:
      required: true
  - type: input
    id: versions-affected
    attributes:
      label: Versions Affected
      description: "Indicate the versions that this bug is related to."
    validations:
      required: true
  - type: checkboxes
    id: platforms-affected
    attributes:
      label: Platforms Affected
      description: "Check the platforms that this bug is related to."
      options:
        - label: iOS
          required: false
        - label: Android
          required: false
        - label: Web
          required: false
  - type: textarea
    id: notes
    attributes:
      label: Notes / Comments
      description: "Anything else we need to know to help? Include it here."
    validations:
      required: false
